		      $(document).ready(function(){
				      $("#p1,#p2,#p3,#p4").hide();
			      $("#t1").focusin(function(){
				      $(this).css("background-color","#e8edff");
				      });
			      
			      $("#t1").focusout(function(){
				      $(this).css("background","url({{=URL(request.application,'static','images/bck.jpg')}})");
				      });
			      $("#l1").click(function(){
				      $(".level2").hide();
				      $(".level1").show();
				      });
			     
			      $("#l2").click(function(){
				      $(".level1").hide();
				      $(".level2").show();
				      });
			      $("#both").click(function(){
				      $(".level1").show();
				      $(".level2").show();
				      });
			      $("#hid1").mouseover(function(){
					      $("#p1").slideDown("fast");
					      });
			      $("#hid2").mouseover(function(){
					      $("#p2").slideDown("fast");
					      });
			      $("#hid3").mouseover(function(){
					      $("#p3").slideDown("fast");
					      });
			      $("#hid4").mouseover(function(){
					      $("#p4").slideDown("fast");
					      });
			      $("#hid1,#hid2,#hid3,#hid4").mouseout(function(){
					      $("#p1,#p2,#p3,#p4").slideUp("fast");
					      });
			      $("[id$='_i1']").mouseover(function(){
					      $("[id$='_i1']").css("background-color","#007f7f");
					      $("[id$='_i1']").css("color","#FFFFFF");
					      });
			      $("[id$='_i1']").mouseout(function(){
					      $("[id$='_i1']").css("background-color","#e8edff");
					      $("[id$='_i1']").css("color","#669");
					      });
			      $("[id$='_l2i']").mouseover(function(){
					      $("[id$='_l2i']").css("background-color","#007f7f");
					      $("[id$='_l2i']").css("color","#FFFFFF");
					      });
			      $("[id$='_l2i']").mouseout(function(){
					      $("[id$='_l2i']").css("background-color","#e8edff");
					      $("[id$='_l2i']").css("color","#669");
					      });
			      $("[id$='_d1']").mouseover(function(){
					      $("[id$='_d1']").css("background-color","#007f7f");
					      $("[id$='_d1']").css("color","#FFFFFF");
					      });
			      $("[id$='_d1']").mouseout(function(){
					      $("[id$='_d1']").css("background-color","#e8edff");
					      $("[id$='_d1']").css("color","#669");
					      });
			      $("[id$='_l2d']").mouseover(function(){
					      $("[id$='_l2d']").css("background-color","#007f7f");
					      $("[id$='_l2d']").css("color","#FFFFFF");
					      });
			      $("[id$='_l2d']").mouseout(function(){
					      $("[id$='_l2d']").css("background-color","#e8edff");
					      $("[id$='_l2d']").css("color","#669");
					      });
			      $(".d1_rd").mouseover(function(){
					      $(".d1_rd").css("background-color","#007f7f");
					      $(".d1_rd").css("color","#FFFFFF");
					      });
			      $(".d1_rd").mouseout(function(){
					      $(".d1_rd").css("background-color","#e8edff");
					      $(".d1_rd").css("color","#669");
					      });
			      $(".d1_wr").mouseover(function(){
					      $(".d1_wr").css("background-color","#007f7f");
					      $(".d1_wr").css("color","#FFFFFF");
					      });
			      $(".d1_wr").mouseout(function(){
					      $(".d1_wr").css("background-color","#e8edff");
					      $(".d1_wr").css("color","#669");
					      });
			      $(".l2d_rd").mouseover(function(){
					      $(".l2d_rd").css("background-color","#007f7f");
					      $(".l2d_rd").css("color","#FFFFFF");
					      });
			      $(".l2d_rd").mouseout(function(){
					      $(".l2d_rd").css("background-color","#e8edff");
					      $(".l2d_rd").css("color","#669");
					      });
			      $(".l2d_wr").mouseover(function(){
					      $(".l2d_wr").css("background-color","#007f7f");
					      $(".l2d_wr").css("color","#FFFFFF");
					      });
			      $(".l2d_wr").mouseout(function(){
					      $(".l2d_wr").css("background-color","#e8edff");
					      $(".l2d_wr").css("color","#669");
					      });
			      $("#hid1,#hid2,#hid3,#hid4").mouseover(function(){
					      $(this).css("background-color","#007f7f");
					      });
			      $("#hid1,#hid2,#hid3,#hid4").mouseout(function(){
					      $(this).css("background","#f6f6ee url(../images/bck.jpg)");
					      });
		      });

			     	 
