

class cachesimulator$4 implements java.awt.event.ActionListener {
	cachesimulator$4(cachesimulator arg0) {
		this.this$0 = arg0;
	}

	public void actionPerformed(java.awt.event.ActionEvent arg0) {
		cachesimulator.access$300(this.this$0, arg0);
	}
}

/*
 * Generated by DecoJer 0.9.1, a Java-bytecode decompiler.
 * DecoJer Copyright (C) 2009-2013 André Pankraz. All Rights Reserved.
 *
 * Class File Version: 50 (Java 6)
 * Source File Name: cachesimulator.java
 */